# SELECT C.ID
# FROM ECOLI_DATA C
# JOIN ECOLI_DATA P 
#   ON C.PARENT_ID = P.ID -- c 의 부모 찾음 
# JOIN ECOLI_DATA G 
#   ON P.PARENT_ID = G.ID -- p 의 부모 찾음 
# WHERE G.PARENT_ID IS NULL -- g null 이면 최초개체 
# ORDER BY C.ID ASC;


# 다른 풀이 

WITH RECURSIVE ECOLI_SEARCH AS (
    
    # 시작쿼리 
    SELECT ID, PARENT_ID, 1 AS DEPTH
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    # 재귀 쿼리 
    SELECT E.ID, E.PARENT_ID, S.DEPTH + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_SEARCH S ON E.PARENT_ID = S.ID
)

SELECT ID
FROM ECOLI_SEARCH
WHERE DEPTH = 3
ORDER BY ID
