SELECT C.ID
FROM ECOLI_DATA C
JOIN ECOLI_DATA P 
  ON C.PARENT_ID = P.ID -- c 의 부모 찾음 
JOIN ECOLI_DATA G 
  ON P.PARENT_ID = G.ID -- p 의 부모 찾음 
WHERE G.PARENT_ID IS NULL -- g null 이면 최초개체 
ORDER BY C.ID ASC;